"""Orquestación y caché: la frontera entre el cálculo puro y la interfaz."""

from servicios.cache import (
    agregar_por_semana,
    aporte_conjunto_por_objetivo,
    aporte_por_grupo,
    aporte_por_variable,
    cargar_panel,
    comparar_familias,
    construir_informe,
    correlacion_control_poda,
    correlacion_parcial,
    correlaciones_con_objetivo,
    correlaciones_semanales,
    descomponer_frutos_peso,
    descomposicion_varianza,
    diagnostico_ventanas,
    entrenar,
    forma_de_la_relacion,
    ganancia_cuadratica,
    honesto_por_objetivo,
    leer_archivo,
    mejor_rezago_por_variable,
    placebo,
    por_modulo,
    resumen_picos_frutos_peso,
    rezago_floracion,
    rezagos,
    rezagos_todos,
    signo_depende_de_la_ventana,
    tabla_validacion,
    tamano_efectivo,
    trayectorias_frutos_peso,
    veredicto,
    verificar_consistencia,
)

__all__ = [
    "agregar_por_semana", "aporte_conjunto_por_objetivo", "aporte_por_grupo",
    "aporte_por_variable", "cargar_panel", "comparar_familias",
    "construir_informe", "correlacion_control_poda", "correlacion_parcial", "correlaciones_con_objetivo",
    "correlaciones_semanales", "descomponer_frutos_peso", "descomposicion_varianza",
    "diagnostico_ventanas",
    "entrenar", "forma_de_la_relacion", "ganancia_cuadratica", "honesto_por_objetivo",
    "leer_archivo",
    "mejor_rezago_por_variable", "placebo",
    "por_modulo", "rezago_floracion", "rezagos", "rezagos_todos", "resumen_picos_frutos_peso",
    "signo_depende_de_la_ventana",
    "tabla_validacion", "tamano_efectivo", "trayectorias_frutos_peso", "veredicto",
    "verificar_consistencia",
]
