"""Pronóstico temporal, evidencia y gobierno de modelos de Aqu Anqa."""

from importlib import import_module

_LAZY_ATTRS = {
    "DatosProyeccion": (".contratos", "DatosProyeccion"),
    "FuenteInfo": (".contratos", "FuenteInfo"),
    "ResultadoTorneo": (".contratos", "ResultadoTorneo"),
    "ProjectionConfig": (".engine", "ProjectionConfig"),
    "ProjectionNotReady": (".engine", "ProjectionNotReady"),
    "ProjectionScenario": (".engine", "ProjectionScenario"),
    "proyectar_desde_corte": (".engine", "proyectar_desde_corte"),
    "replay_historico_ciego": (".engine", "replay_historico_ciego"),
    "AdaptadorOpenMeteo": (".clima_futuro", "AdaptadorOpenMeteo"),
    "PronosticoClima": (".clima_futuro", "PronosticoClima"),
    "resolver_horizonte_climatico": (".clima_futuro", "resolver_horizonte_climatico"),
    "NOMBRE_MODELO_HIBRIDO": (".hibrido_legacy", "NOMBRE_MODELO"),
    "backtest_hibrido_v1": (".hibrido_legacy", "backtest_hibrido_v1"),
    "backtest_macro_legacy_v1": (".hibrido_legacy", "backtest_macro_legacy_v1"),
    "construir_curva_historica": (".hibrido_legacy", "construir_curva_historica"),
    "proyectar_hibrido_v1": (".hibrido_legacy", "proyectar_hibrido_v1"),
    "NOMBRE_MODELO_PARAMETROS_ASOF": (".hibrido_parametros_asof", "NOMBRE_MODELO"),
    "VERSION_MODELO_PARAMETROS_ASOF": (".hibrido_parametros_asof", "VERSION_MODELO"),
    "ConfiguracionParametrosAsOf": (".hibrido_parametros_asof", "ConfiguracionParametrosAsOf"),
    "aprender_desplazamiento": (".hibrido_parametros_asof", "aprender_desplazamiento"),
    "backtest_hibrido_parametros_asof": (
        ".hibrido_parametros_asof",
        "backtest_hibrido_parametros_asof",
    ),
    "construir_snapshot_parametros": (".hibrido_parametros_asof", "construir_snapshot_parametros"),
    "ejecutar_emision_parametros_asof": (
        ".hibrido_parametros_asof",
        "ejecutar_emision_parametros_asof",
    ),
    "normalizar_parametros_excel": (".hibrido_parametros_asof", "normalizar_parametros_excel"),
    "seleccionar_gdd_config": (".hibrido_parametros_asof", "seleccionar_gdd_config"),
    "seleccionar_peso_macro": (".hibrido_parametros_asof", "seleccionar_peso_macro"),
    "sha256_archivo": (".hibrido_parametros_asof", "sha256_archivo"),
    "cargar_parametros_historicos": (".parametros_excel", "cargar_parametros_historicos"),
    "cargar_parametros_libro": (".parametros_excel", "cargar_parametros_libro"),
    "seleccionar_libros_parametros": (".parametros_excel", "seleccionar_libros_parametros"),
    "EscenarioFenologico": (".fenologico_v1", "EscenarioFenologico"),
    "ResultadoFenologico": (".fenologico_v1", "ResultadoFenologico"),
    "aplicar_escenario_fenologico": (".fenologico_v1", "aplicar_escenario_fenologico"),
    "backtest_fenologico_v1": (".fenologico_v1", "backtest_fenologico_v1"),
    "proyectar_fenologico_v1": (".fenologico_v1", "proyectar_fenologico_v1"),
    "metricas_pronostico": (".metricas", "metricas_pronostico"),
    "OccurrenceConfig": (".ocurrencia", "OccurrenceConfig"),
    "estimar_ocurrencia": (".ocurrencia", "estimar_ocurrencia"),
    "LoteParametrosProyeccion": (".motor_proyeccion_semanal", "LoteParametrosProyeccion"),
    "RegistroBDProy": (".motor_proyeccion_semanal", "RegistroBDProy"),
    "ajustar_dia_habil": (".motor_proyeccion_semanal", "ajustar_dia_habil"),
    "calcular_fechas_reingreso": (".motor_proyeccion_semanal", "calcular_fechas_reingreso"),
    "extraer_fechas_pasadas": (".motor_proyeccion_semanal", "extraer_fechas_pasadas"),
    "ejecutar_proyeccion_semanal_dataframe": (
        ".motor_proyeccion_semanal",
        "ejecutar_proyeccion_semanal_dataframe",
    ),
    "generar_matriz_resumen_pdi": (".motor_proyeccion_semanal", "generar_matriz_resumen_pdi"),
    "norm_cdf": (".motor_proyeccion_semanal", "norm_cdf"),
    "proyectar_lote_pasadas": (".motor_proyeccion_semanal", "proyectar_lote_pasadas"),
    "semana_iso_21": (".motor_proyeccion_semanal", "semana_iso_21"),
    "ResultadoValidacionOperativa": (".validacion_operativa", "ResultadoValidacionOperativa"),
    "validar_libro_operativo": (".validacion_operativa", "validar_libro_operativo"),
    "validar_libros_semana": (".validacion_operativa", "validar_libros_semana"),
    "banda_horizonte": (".versiones", "banda_horizonte"),
    "parsear_version": (".versiones", "parsear_version"),
    "construir_backtest_r09": (".backtest", "construir_backtest_r09"),
    "seleccionar_versiones_oficiales": (".backtest", "seleccionar_versiones_oficiales"),
    "LIBROS_OPERATIVOS": (".operativo_excel", "LIBROS_OPERATIVOS"),
    "MODELO_OPERATIVO_ACTUAL": (".operativo_excel", "MODELO_OPERATIVO_ACTUAL"),
    "construir_modelo_operativo_excel": (".operativo_excel", "construir_modelo_operativo_excel"),
    "datos_proyeccion_operativo": (".operativo_excel", "datos_proyeccion_operativo"),
    "seleccionar_libros_operativos": (".operativo_excel", "seleccionar_libros_operativos"),
}


def __getattr__(name: str):
    try:
        modulo, atributo = _LAZY_ATTRS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    valor = getattr(import_module(modulo, __name__), atributo)
    globals()[name] = valor
    return valor


def __dir__():
    return sorted(set(globals()) | set(__all__) | set(_LAZY_ATTRS))


__all__ = [
    "DatosProyeccion",
    "FuenteInfo",
    "ResultadoTorneo",
    "ProjectionConfig",
    "ProjectionNotReady",
    "ProjectionScenario",
    "proyectar_desde_corte",
    "replay_historico_ciego",
    "NOMBRE_MODELO_HIBRIDO",
    "backtest_hibrido_v1",
    "backtest_macro_legacy_v1",
    "construir_curva_historica",
    "proyectar_hibrido_v1",
    "NOMBRE_MODELO_PARAMETROS_ASOF",
    "VERSION_MODELO_PARAMETROS_ASOF",
    "ConfiguracionParametrosAsOf",
    "backtest_hibrido_parametros_asof",
    "ejecutar_emision_parametros_asof",
    "construir_snapshot_parametros",
    "normalizar_parametros_excel",
    "seleccionar_peso_macro",
    "seleccionar_gdd_config",
    "aprender_desplazamiento",
    "sha256_archivo",
    "seleccionar_libros_parametros",
    "cargar_parametros_libro",
    "cargar_parametros_historicos",
    "OccurrenceConfig",
    "EscenarioFenologico",
    "ResultadoFenologico",
    "aplicar_escenario_fenologico",
    "AdaptadorOpenMeteo",
    "PronosticoClima",
    "resolver_horizonte_climatico",
    "backtest_fenologico_v1",
    "proyectar_fenologico_v1",
    "estimar_ocurrencia",
    "banda_horizonte",
    "construir_backtest_r09",
    "metricas_pronostico",
    "parsear_version",
    "seleccionar_versiones_oficiales",
    "LoteParametrosProyeccion",
    "RegistroBDProy",
    "norm_cdf",
    "semana_iso_21",
    "ajustar_dia_habil",
    "calcular_fechas_reingreso",
    "extraer_fechas_pasadas",
    "proyectar_lote_pasadas",
    "ejecutar_proyeccion_semanal_dataframe",
    "generar_matriz_resumen_pdi",
    "ResultadoValidacionOperativa",
    "validar_libro_operativo",
    "validar_libros_semana",
    "LIBROS_OPERATIVOS",
    "MODELO_OPERATIVO_ACTUAL",
    "construir_modelo_operativo_excel",
    "datos_proyeccion_operativo",
    "seleccionar_libros_operativos",
]
