version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$REGISTRY"
  build:
    commands:
      - docker build -f backend/campo-api/Dockerfile -t "$REGISTRY/aquanqa/api:$RELEASE" .
      - docker build -f infra/aws/migration.Dockerfile -t "$REGISTRY/aquanqa/migration:$RELEASE" .
  post_build:
    commands:
      - docker push "$REGISTRY/aquanqa/api:$RELEASE"
      - docker push "$REGISTRY/aquanqa/migration:$RELEASE"
